ci: use exit code solution and initialize variable

diff --git a/.github/workflows/lighthouse.yml b/.github/workflows/lighthouse.yml
--- a/.github/workflows/lighthouse.yml
+++ b/.github/workflows/lighthouse.yml
@@ -361,22 +361,24 @@ jobs:
 
       # each json is an array of objects x, each x.auditId property is a unique ID of assertion
       # verify assertion-results.json and .ls-assertion-results-gs.json are the same
-      - name: 'Verify Gold Standard Performance reached!'
+      # Verify Gold Standard Performance reached!'
+      - name: 'Compare ${{ env.RUNTIME_JSON }} to ${{ env.GOLD_STANDARD_JSON }}'
         if: always()
         env:
           COMPARE: code/scripts/ci-compare-json-arrays.py
         run: |
           chmod +x ${{ env.COMPARE }}
-          ${{ env.COMPARE }} ${RUNTIME_JSON} ${GOLD_STANDARD_JSON} || pass_comparison=0
+          exit_code=0
+          ${{ env.COMPARE }} ${{ env.RUNTIME_JSON }} ${{ env.GOLD_STANDARD_JSON }} || exit_code=1
 
-          if [ $pass_comparison -eq 0 ]; then
-            echo "[ERROR] Lighthouse Job FAILED!"
-            echo " - Lighthouse Job did not reach Gold Standard!" >> $GITHUB_STEP_SUMMARY
-            exit 1
-          else
+          if [ $exit_code -eq 0 ]; then
             echo "[INFO] Lighthouse Job PASSED!"
             echo " - Lighthouse Job reached Gold Standard!" >> $GITHUB_STEP_SUMMARY
+          else
+            echo "[ERROR] Lighthouse Job FAILED!"
+            echo " - Lighthouse Job did not reach Gold Standard!" >> $GITHUB_STEP_SUMMARY
           fi
+          exit $exit_code
           
 
         # # use jq create two objects with keys being the x.auditId 
