ci: improve Bundle Test Job trigger condition and add Sanity Check

diff --git a/.github/workflows/test-bundle.yml b/.github/workflows/test-bundle.yml
--- a/.github/workflows/test-bundle.yml
+++ b/.github/workflows/test-bundle.yml
@@ -8,8 +8,12 @@ on:
         required: true
         type: string
       bundle_size:
-        description: "Expected Bundle Size, computed by 'du -sh'"
+        description: "Expected Bundle Size on disk, computed by 'du -sh'"
         type: string
+        required: true
+      expected_number_of_files:
+        description: 'Expected Number of Files in the Bundle, used for testing'
+        type: number
         required: true
       # Optional Inputs
       bundle_size_acceptance:
@@ -173,5 +177,30 @@ jobs:
         run: |
           if [ ! -d '~partytown' ]; then
             echo "[ERROR] ~partytown directory is missing!"
+            exit 1
+          fi
+
+      # Test 7: Verify the presence of a favicon
+      # - name: Verify favicon is present
+      #   working-directory: ${{ env._BUNDLE_DIR }}
+      #   run: |
+      #     if [ ! -f favicon.ico ]; then
+      #       echo "[ERROR] favicon.ico is missing!"
+      #       exit 1
+      #     fi
+
+      # Strict Sanity Check for all expected files
+      # find Directory_name -ls
+      - name: 'Sanity Check that exactly ${{ inputs.expected_number_of_files }} files are included in the bundle'
+        env:
+          NB_EXPECTED_FILES: 39
+        run: |
+          NB_FILES=$(find ${{ env._BUNDLE_DIR }} -type f -ls | wc -l)
+          echo "[INFO] Number of Files in Bundle: $NB_FILES"
+          echo " - Number of Files in Web Bundle: **${NB_FILES}**" >> $GITHUB_STEP_SUMMARY
+
+          if [ $NB_FILES -ne ${{ inputs.expected_number_of_files }} ]; then
+            echo "[ERROR] Found ${NB_FILES} files in web bundle, but ${{ inputs.expected_number_of_files }} are expected"
+            echo "exiting with status code 1"
             exit 1
           fi
